export const jakalikyRef = {
    "static agile": 5,
    "probability": 15,
    "bonz": 8,
    "zlaty bludistak": 69,
    "agilni veta": 1,
  }

  export const agilniSlova = [
    "manifest",
    "jakal",
    "finish",
    "user",
    "story",
    "backlog",
    "sprint",
    "scrum",
    "master",
    "product",
    "owner",
    "daily",
    "standup",
    "velocity",
    "burndown",
    "chart",
    "retrospective",
    "continuous",
    "integration",
    "pair",
    "programming",
    "kanban",
    "epics",
    "agile",
    "manifesto",
    "refactoring",
    "minimum",
    "viable",
    "product",
    "acceptance",
    "criteria",
    "increment",
    "timeboxing",
    "sprint",
    "planning",
    "product",
    "backlog",
    "refinement",
    "definition",
    "of",
    "done",
    "scrum",
    "of",
    "scrums",
    "feature",
    "driven",
    "development",
    "test",
    "driven",
    "develop",
    "continuous",
    "deploy",
    "lean",
    "agil",
    "coach",
    "waterfall"
  ];
  
  